### PR TITLE
Fixed Schematic building location issue for SpongeSchematics

### PR DESCRIPTION
**Pull request by Technerder**
https://github.com/CrystalGamesMC/Scaffolding/issues/2

### CODE REVIEW

**Comment by Technerder** [comment]
Thanks for merging, when do you think you'll be able to release a new maven repo artifact/build that contain the changes from this PR?

**Comment by LooFifteen** [comment]
Whoops, normally have CI to do that for me, should be all done now.

**Comment by Technerder** [comment]
I was expecting it to be under a new snapshot version but a quick Gradle dependency refresh fixed it! Thanks again.

**Comment by LooFifteen** [comment]
Once it's stable versions will start to be bumped.

**Pull request merged**
